services:

  mysql:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: urban
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-puserpass"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    build: ./backend
    container_name: backend_service
    restart: always
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: userpass
      DB_NAME: urban
      JWT_SECRET: Canob19742013
      JWT_EXPIRES_IN: 24h
      EMAIL_USER: urbansneakershelp@gmail.com
      EMAIL_PASSWORD: ghqb mxka mfmj zofg 
      FRONTEND_URL: http://localhost:81
      GITHUB_CLIENT_ID: Ov23lifEAJCr9kGFhwP4
      GITHUB_CLIENT_SECRET: ffd49532c203baabc6a6a5f16d84bd8fa5a8c772
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/uploads:/app/uploads
    depends_on:
      mysql:
        condition: service_healthy

  frontend:
    build: 
      context: ./frontend
      args:
        - VITE_GITHUB_CLIENT_ID=Ov23lifEAJCr9kGFhwP4
    container_name: frontend_service
    restart: always
    ports:
      - "81:80"
    volumes:
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

volumes:
  mysql_data:
