title: Urban Sneakers Web Page
description: Documentaci칩n de la p치gina web de Urban Sneakers - Ecommerce de zapatillas urbanas
theme: jekyll-theme-cayman

# Configuraci칩n importante para Jekyll
defaults:
  -
    scope:
      path: "" # aplica a todos los archivos
    values:
      layout: default

# Especificar que los archivos .md deben ser procesados
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Configurar la p치gina principal
index_page: index.md 